name: Build C++
on:
  push:
    paths:
    - 'client_server/**'
    - '.github/workflows/**'
  pull_request:
    paths:
    - 'client_server/**'
    - '.github/workflows/**'
jobs:
  server-windows-cygwin:
    name: Build server on Windows/Cygwin
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install cygwin with chocolatey
      run: |
        choco install --no-progress cygwin
        echo "C:\tools\cygwin\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "C:\tools\cygwin\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - uses: actions/cache@v1
      with:
        path: C:\tools\cygwin\package
        key: ${{ runner.os }}-cygwin-package-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-cygwin-package-
    - name: Install dependencies with cygwin
      shell: cmd
      run: |
        C:\tools\cygwin\cygwinsetup.exe -qgnNdO -R C:/tools/cygwin -l C:/tools/cygwin/package -s http://mirrors.kernel.org/sourceware/cygwin/ -P cmake,make,gcc-core,gcc-g++

    - name: Build client
      shell: cmd
      continue-on-error: true # Currently, the client builds only on Linux
      run: |
        cd client_server/client
        cmake CMakeLists.txt
        make

    - name: Build server
      shell: cmd
      run: |
        cd client_server/server
        cmake CMakeLists.txt
        make


  client-ubuntu:
    name: Build client on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build client
      run: |
        cd client_server/client
        cmake CMakeLists.txt
        make
